import XCTest
@testable import vClips

final class PasteboardPolicyTests: XCTestCase {
    func test_allowsPlainTextTypes() {
        XCTAssertTrue(PasteboardPolicy.shouldCapture(types: ["public.utf8-plain-text"]))
    }

    func test_blocksConcealedType() {
        let types = ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]
        XCTAssertFalse(PasteboardPolicy.shouldCapture(types: types))
    }

    func test_blocksTransientType() {
        let types = ["org.nspasteboard.TransientType", "public.utf8-plain-text"]
        XCTAssertFalse(PasteboardPolicy.shouldCapture(types: types))
    }

    func test_blocksAutoGeneratedType() {
        let types = ["org.nspasteboard.AutoGeneratedType"]
        XCTAssertFalse(PasteboardPolicy.shouldCapture(types: types))
    }
}
