import Foundation

enum PasteboardPolicy {
    static let blockedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func shouldCapture(types: [String]) -> Bool {
        for type in types where blockedTypes.contains(type) {
            return false
        }
        return true
    }
}
